# cert-frontend.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-cert
  namespace: istio-ingress
spec:
  secretName: frontend-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "askneu.com"
  dnsNames:
    - "askneu.com"
  usages:
    - digital signature
    - key encipherment
    - server auth