name: Deploy Airflow Pipeline to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'Data Pipeline/dags/**'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  deploy-airflow:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      IMAGE_NAME: airflow-pipeline
      REGION: us-central1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Google Cloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f Dockerfile .

      - name: Push Docker Image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.IMAGE_NAME }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory 2Gi \
            --cpu 1 \
            --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},GCP_SA_KEY='${{ secrets.GCP_SA_KEY }}',PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      - name: Trigger Airflow DAG
        run: |
          curl -X POST "https://${{ env.REGION }}-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/${{ secrets.GCP_PROJECT_ID }}/services/${{ env.IMAGE_NAME }}:run" \
          -H "Authorization: Bearer $(gcloud auth print-identity-token)" \
          -H "Content-Type: application/json" \
          -d '{"conf": {"trigger_file": "urls.xls"}}'

      - name: Clean up old images
        run: |
          gcloud container images delete gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }} --force-delete-tags --quiet || true
